## template: jinja
#cloud-config


{% set wsuser = "ws-user" %}

groups:
  - {{ wsuser }}

runcmd:
  - mkdir /root/tests/
  - myvar=`echo 'This is my var'`
  - echo $myvar > /root/tests/myvar
  - echo {{ ds.meta_data.hostname }} > /root/tests/hostname
  
