## template: jinja
#cloud-config


{% set wsuser = "ws-user" %}

runcmd:
  - sed -i '2i "test":"passed",' /run/cloud-init/instance-data-sensitive.json
  - sleep 10


users:
  - name: {{ wsuser }}
    lock_passwd: True
    gecos: {{ wsuser }}
    groups: [adm, audio, cdrom, dialout, dip, floppy, lxd, netdev, plugdev, sudo, video]
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    shell: /bin/bash
    ssh_authorized_keys: {{ public_ssh_keys }}

# package_upgrade: True

runcmd:
  - mkdir /root/tests/
  - myvar=`echo 'This is my var'`
  - echo $myvar > /root/tests/myvar
  - echo {{ ds.meta_data.hostname }} > /root/tests/hostname
  - echo {{ test }} > /root/tests/pong
  
