## template: jinja
#cloud-config

runcmd:
  - echo 'fuck' > /root/fuck
  - echo 'fist' > /root/first
  - echo '{{ v1.region }}' > /root/region
  - echo '{{ ds.meta-data.ami-id }}' > /root/ami_id
  - echo '{{ default_username }}' > /root/username
